### ISSUE TITLE
404 Not Found !! The resource could not be found.  /img/glyphicons-halflings.png

### ISSUE THREAD

**Issue by abdulwahid24** [Kotti/deform_bootstrap#64]
hi guys,

great afford for such beautiful app. Recently i have come across to this error

404 Not Found !! The resource could not be found.  /img/glyphicons-halflings.png

What i found is that there no resource included in deform_boostrap package so i resolved my including these img files manually by placing this glyphicons-halflings.png & glyphicons-halflings-white.png files into static dir of deform_boostap and changed the path in deform_bootstrap.css.

So it will be great if you guys fix this so that everyone will not face the same problem.
![screenshot from 2013-08-01 15 00 12](https://f.cloud.github.com/assets/4718496/922836/c091ee6e-ff35-11e2-869d-21417a129da5.png)

**Comment by dnouri** [comment]
This has been fixed just three days ago.  See #61

**Comment by abdulwahid24** [comment]
i just did a reinstall using pip such as

pip uninstall deform_bootstap
and then
pip install deform_bootstrap

but still missing img folder in static dir. :(

Please help me to resolve this.

**Comment by disko** [comment]
On 07.08.2013, at 10:40, Abdul Wahid notifications@github.com wrote:

> pip uninstall deform_bootstap
> and then
> pip install deform_bootstrap
> 
> but still missing img folder in static dir. :(

You need to install from the Github repo until a new release (including the fix that @dnouri mentioned) is available on PyPI.

**Comment by abdulwahid24** [comment]
i did now its working...thanks.
